[tool.poetry]
name = "podcaster-ai"
version = "0.1.0"
description = "Project analyzing podcast scores with explainable AI and deep learning."
authors = ["Chase Yakaboski <chase.th@dartmouth.edu>"]
packages = [{include = "podcaster_ai"}]

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
boxsdk = {extras = ["jwt"], version = "^3.4.0"}
pandas = "^1.4.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
test = 'scripts:test'
